// <auto-generated />
using CaoDuyPhuoc132.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CaoDuyPhuoc132.Migrations
{
    [DbContext(typeof(CaoDuyPhuoc132Context))]
    [Migration("20211216011512_create_table_CDP")]
    partial class create_table_CDP
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CaoDuyPhuoc132.Models.CDP0132", b =>
                {
                    b.Property<string>("CDPId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("CDPGender")
                        .HasColumnType("bit");

                    b.Property<string>("CDPName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CDPId");

                    b.ToTable("CDP0132");
                });

            modelBuilder.Entity("CaoDuyPhuoc132.Models.UniversityCDP132", b =>
                {
                    b.Property<int>("UniversityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UniversityName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UniversityId");

                    b.ToTable("UniversityCDP132");
                });
#pragma warning restore 612, 618
        }
    }
}
